spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cmf_db
    username: root
    password: root123414
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update