spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cmf_db
    username: root
    password: root123414
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
  autoconfigure: # 로컬에서 실행할 때는 Redis와 Session 설정을 제외
    exclude:
      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
      - org.springframework.boot.autoconfigure.session.SessionAutoConfiguration
